# Generated by Django 5.1.6 on 2025-03-01 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='imagw',
            new_name='image',
        ),
    ]
